/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.crm.gui;

//import com.mycompany.crm.gui.*;
import com.mycompany.crm.exceptions.ComandaException;
import com.mycompany.crm.validator.Validations;
import com.mysql.cj.xdevapi.Schema;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.openide.util.Exceptions;

/**
 *
 * @author admin
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    int xMouse, yMouse;
    ResourceBundle bundle;

    public MenuPrincipal() {
        initComponents();
        textBienvenida.setText(Validations.getInstance().valGetBundle().getString("MSG_BIENVENIDA"));
        bundle = Validations.getInstance().valGetBundle();
        btnJugar.setText(bundle.getString("BTN_PLAY"));
        btnRanking.setText(bundle.getString("BTN_RANKING"));
        btnBorrarCuenta.setText(bundle.getString("BTN_DELETE_ACCOUNT"));
        cerrarSesionBtn.setText(bundle.getString("BTN_EXIT"));
    }
    public void cambiarPanel(JPanel m){
        m.setSize(630, 460);
        m.setLocation(0, 0);


        contenido.removeAll();
        contenido.add(m,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        bg = new javax.swing.JPanel();
        contenido = new javax.swing.JPanel();
        textBienvenida = new javax.swing.JLabel();
        cerrarSesionBtn = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        exitBtn = new javax.swing.JPanel();
        exitText = new javax.swing.JLabel();
        btnRanking = new javax.swing.JButton();
        btnBorrarCuenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        bg.setBackground(new java.awt.Color(0, 51, 102));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenido.setBackground(new java.awt.Color(204, 204, 255));

        textBienvenida.setFont(new java.awt.Font("Roboto Thin", 3, 36)); // NOI18N
        textBienvenida.setText("Bienvenido a Whats BUSCAMINAS");

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenidoLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(textBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(textBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        bg.add(contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 630, 460));

        cerrarSesionBtn.setText("Cerrar Sesión");
        cerrarSesionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionBtnActionPerformed(evt);
            }
        });
        bg.add(cerrarSesionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 400, 147, 36));

        btnJugar.setText("JUGAR");
        btnJugar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        bg.add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 147, 34));

        exitBtn.setBackground(new java.awt.Color(204, 204, 204));

        exitText.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        exitText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitText.setText("X");
        exitText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitText, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitText, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        btnRanking.setText("RANKING");
        btnRanking.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRankingActionPerformed(evt);
            }
        });
        bg.add(btnRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 147, 32));

        btnBorrarCuenta.setText("BORRAR CUENTA");
        btnBorrarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarCuentaActionPerformed(evt);
            }
        });
        bg.add(btnBorrarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 140, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(header, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 421, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarSesionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionBtnActionPerformed
        LoginFrame l = new LoginFrame();
        l.setSize(810  , 500);
        l.setLocationRelativeTo(null);
        l.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_cerrarSesionBtnActionPerformed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
//        ListaClientes l = new ListaClientes();
//        cambiarPanel(l);
        Jugar3 p = new Jugar3(10,10,10);
        cambiarPanel(p);
//        p.setSize(663, 566);
//        p.setLocation(0, 0);
//
//
//        contenido.removeAll();
//        contenido.add(p,BorderLayout.CENTER);
//        contenido.revalidate();
//        contenido.repaint();
    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRankingActionPerformed
        Ranking2 e = new Ranking2();
        cambiarPanel(e);
    }//GEN-LAST:event_btnRankingActionPerformed

    private void exitTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextMouseExited
        //        exitBtn.setBackground(new Color(0,51,102));
        exitText.setForeground(Color.black);
    }//GEN-LAST:event_exitTextMouseExited

    private void exitTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextMouseEntered
        //        exitBtn.setBackground(Color.red);
        exitText.setForeground(Color.red);
    }//GEN-LAST:event_exitTextMouseEntered

    private void exitTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTextMouseClicked

    private void btnBorrarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarCuentaActionPerformed

        //Borrar Cuenta
        
        int confirmacion = JOptionPane.showConfirmDialog(
        this, 
        Validations.getInstance().valGetBundle().getString("MSG_CONFIRMAR_BORRADO"), 
        Validations.getInstance().valGetBundle().getString("MSG_TITULO_BORRADO"), 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.WARNING_MESSAGE
    );

    if (confirmacion == JOptionPane.YES_OPTION) {
            try {
                Validations.getInstance().valBajaUser(); // Llamar al método que ya tienes hecho
                javax.swing.JOptionPane.showMessageDialog(this, Validations.getInstance().valGetBundle().getString("MSG_CUENTA_BORRADA") ,"MESSAGE",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                LoginFrame l = new LoginFrame();
                l.setSize(810  , 500);
                l.setLocationRelativeTo(null);
                l.setVisible(true);
                this.dispose();

            } catch (ComandaException ex) {
                javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage() ,"ERROR",javax.swing.JOptionPane.ERROR_MESSAGE);

            }
    }
        
    }//GEN-LAST:event_btnBorrarCuentaActionPerformed

                                   

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnBorrarCuenta;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnRanking;
    private javax.swing.JButton cerrarSesionBtn;
    private javax.swing.JPanel contenido;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitText;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel textBienvenida;
    // End of variables declaration//GEN-END:variables
}
